development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

staging:
  adapter: mysql2
  host: localhost
  database: <%= ENV["TOUKO_DB_DATABASE"] %>
  username: <%= ENV["TOUKO_DB_USERNAME"] %>
  password: <%= ENV["TOUKO_DB_PASSWORD"] %>
  pool: 5

production:
  adapter: mysql2
  host: localhost
  database: <%= ENV["TOUKO_DB_DATABASE"] %>
  username: <%= ENV["TOUKO_DB_USERNAME"] %>
  password: <%= ENV["TOUKO_DB_PASSWORD"] %>
  pool: 5
